#ifndef TVR_CONSTANTS
#define TVR_CONSTANTS

// General
#define VERSION_STRING  "TwometerVR FW v2.0.2"
#define MANUFACTURER_ID "TVR"

// Sensor
#define SENSOR_USE_COMPASS 1
#define SENSOR_PERIOD_MS   12
#define SENSOR_PERIOD_US   SENSOR_PERIOD_MS * 1000
#define TICK_PERIOD_US     SENSOR_PERIOD_US / 2

#endif