ConfigVersion: 2

# Hardware config
Hardware:
    VideoSource: PSEye
    SphereSize: 0.04
    ColorProfiles:
        Red:
            - Minimum: { H: 0, S: 150, V: 69 }
              Maximum: { H: 20, S: 255, V: 255 }
            - Minimum: { H: 160, S: 150, V: 69 }
              Maximum: { H: 180, S: 255, V: 255 }
        Blue:
            - Minimum: { H: 90, S: 123, V: 59 }
              Maximum: { H: 125, S: 255, V: 255 }
      
# Room config
Offset:
    X: 0
    Y: 1.55
    Z: -1.1
    
# User input config
Input:
    PoseResetButton: Menu
    PoseResetDelay: 0.2
    RefreshRate: 120
    XYPositionSmoothing: 2
    ZPositionSmoothing: 6
    TrackerTimeout: 5
    MinAccuracy: 0.4