ConfigVersion: 2

# Hardware config
Hardware:
    VideoSource: PSEye
    SphereSize: 0.04
    ColorProfiles:
        Red:
            - Minimum: { H: 0, S: 150, V: 69 }
              Maximum: { H: 20, S: 221, V: 255 }
            - Minimum: { H: 110, S: 150, V: 69 }
              Maximum: { H: 127, S: 221, V: 255 }
        Blue:
            - Minimum: { H: 94, S: 143, V: 69 }
              Maximum: { H: 107, S: 226, V: 255 }
      
# Room config
Offset:
    X: 0
    Y: 0
    Z: 0
    
# User input config
Input:
    PoseResetButton: Menu
    PoseResetDelay: 0.2
    RefreshRate: 120
    PositionSmoothing: 2
    TrackerTimeout: 30